import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};

// Translations
const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Nav
    'nav.home': 'Accueil',
    'nav.history': 'Notre Histoire',
    'nav.peoples': 'Peuples',
    'nav.mission': 'Mission & Vision',
    'nav.values': 'Valeurs',
    'nav.contact': 'Contact',
    'nav.team': 'Notre Équipe',
    'nav.donate': 'Faire un Don',
    'nav.team.parrains': 'Haut Patronage Royal et Traditionnel',
    'nav.team.membres_honneur': 'Membres d\'honneur',
    'nav.team.conseil': 'Conseil d\'Administration',
    'nav.team.bureau': 'Bureau Exécutif',
    'nav.team.representants': 'Représentation nationale',
    'nav.team.comite': 'Comité des sages',
    'nav.publications': 'Publications',
    'nav.evenements': 'Événements',
    'nav.ressources': 'Ressources',
    'nav.galerie': 'Galerie',
    'nav.partenaires': 'Partenaires',

    // Hero
    'hero.badge': 'Patrimoine • Culture • Héritage',
    'hero.title1': 'International',
    'hero.title2': 'Mandjara',
    'hero.title3': 'Heritage',
    'hero.subtitle': 'Préserver et transmettre le patrimoine culturel, historique et social des peuples',
    'hero.cta1': 'Découvrir Notre Mission',
    'hero.cta2': 'En Savoir Plus',
    'hero.scroll': 'Découvrir',

    // Index
    'index.explore_badge': 'Explorez Notre Héritage',
    'index.explore_title': 'Découvrez Notre',
    'index.explore_title_highlight': 'Organisation',
    'index.explore_subtitle': 'Naviguez à travers les différentes sections pour en apprendre davantage sur notre mission, nos valeurs et notre engagement culturel.',
    'index.card.history': 'Notre Histoire',
    'index.card.history_desc': 'Découvrez les racines profondes de l\'International Mandjara Heritage et son ancrage dans la culture du peuple Mandjara.',
    'index.card.peoples': 'Les Trois Peuples',
    'index.card.peoples_desc': 'Explorez l\'héritage culturel des Bamoun, Nso\' et Bafia, les trois grands peuples fondateurs.',
    'index.card.mission': 'Notre Mission',
    'index.card.mission_desc': 'Promouvoir, préserver et transmettre le patrimoine culturel pour les générations futures.',
    'index.card.values': 'Nos Valeurs',
    'index.card.values_desc': 'Les principes fondamentaux qui guident chaque décision et action de notre organisation.',
    'index.learn_more': 'En savoir plus',
    'index.team_title': 'Notre Équipe',
    'index.team_desc': 'Rencontrez les leaders engagés qui portent la vision de l\'International Mandjara Heritage.',
    'index.team_link': 'Découvrir l\'équipe',
    'index.join_title': 'Rejoignez-nous',
    'index.join_desc': 'Contactez-nous pour contribuer à la préservation de notre patrimoine culturel.',
    'index.join_link': 'Nous contacter',

    // Context Page
    'context.badge': 'Contexte & Origines',
    'context.title': 'Un Héritage',
    'context.title_highlight': 'Millénaire',
    'context.subtitle': 'Découvrez les racines profondes de l\'International Mandjara Heritage et son ancrage dans l\'histoire et la culture du peuple Mandjara.',
    'context.roots_title': 'Les Racines de Notre',
    'context.roots_highlight': 'Engagement',
    'context.roots_p1': 'L\'International Mandjara Heritage trouve ses racines dans l\'histoire et la culture du peuple Mandjara, un groupe ethnique d\'Afrique centrale ayant façonné son identité, sa langue et ses traditions à travers les siècles.',
    'context.roots_p2': 'Elle s\'inspire de cet héritage pour promouvoir le développement social, culturel et éducatif dans le respect des traditions locales, tout en s\'inscrivant dans une approche contemporaine du développement durable fondé sur quatre piliers : économique, social, environnemental et culturel.',
    'context.roots_p3': 'Cette approche rejoint la Déclaration Universelle de l\'UNESCO sur la diversité culturelle (2001) et la Convention sur la Diversité des Expressions Culturelles (2005).',
    'context.quote': 'La culture est essentielle à la durabilité, à la paix et au bien-être des sociétés.',
    'context.quote_author': 'UNESCO, 2005',
    'context.timeline_title': 'Notre',
    'context.timeline_highlight': 'Histoire',
    'context.timeline.19th': 'XIXe Siècle',
    'context.timeline.19th_title': 'Invention de l\'Écriture Shu-Mom',
    'context.timeline.19th_desc': 'Le Roi Njoya crée un système d\'écriture unique pour le peuple Bamoun.',
    'context.timeline.2001': '2001',
    'context.timeline.2001_title': 'Déclaration UNESCO',
    'context.timeline.2001_desc': 'Déclaration Universelle sur la diversité culturelle.',
    'context.timeline.2005': '2005',
    'context.timeline.2005_title': 'Convention UNESCO',
    'context.timeline.2005_desc': 'Convention sur la Diversité des Expressions Culturelles.',
    'context.timeline.today': 'Aujourd\'hui',
    'context.timeline.today_title': 'International Mandjara Heritage',
    'context.timeline.today_desc': 'Continuité culturelle et développement durable.',
    'context.feature.ancestors': 'Respect des Ancêtres',
    'context.feature.ancestors_desc': 'Honorer la mémoire et les enseignements de ceux qui ont façonné notre identité à travers les siècles.',
    'context.feature.solidarity': 'Solidarité Communautaire',
    'context.feature.solidarity_desc': 'Renforcer les liens entre les générations et les diasporas issues de nos communautés.',
    'context.feature.knowledge': 'Transmission du Savoir',
    'context.feature.knowledge_desc': 'Préserver et partager le patrimoine matériel et immatériel pour les générations futures.',

    // Peoples Page
    'peoples.badge': 'Les Trois Peuples Fondateurs',
    'peoples.title': 'Peuples',
    'peoples.title_highlight': 'Mandjara',
    'peoples.subtitle': 'Découvrez les trois grands peuples du Cameroun qui forment le cœur de l\'International Mandjara Heritage : les Bamoun, les Nso\' et les Bafia.',
    'peoples.founding': 'Peuple Fondateur',
    'peoples.bamoun.name': 'Les Bamoun',
    'peoples.bamoun.region': 'Région du Noun, Cameroun',
    'peoples.bamoun.desc': 'Un patrimoine artistique et culturel exceptionnel, incluant le système d\'écriture inventé par le Roi Njoya à la fin du XIXe siècle.',
    'peoples.bamoun.long_desc': 'Le peuple Bamoun est reconnu mondialement pour son patrimoine artistique et culturel exceptionnel. Le Roi Njoya, figure emblématique, a inventé un système d\'écriture unique appelé Shu-Mom à la fin du XIXe siècle, démontrant le génie créatif de cette civilisation. Le Palais des Rois Bamoun à Foumban reste un témoignage vivant de cette grandeur culturelle.',
    'peoples.bamoun.h1': 'Écriture Shu-Mom inventée par le Roi Njoya',
    'peoples.bamoun.h2': 'Palais Royal de Foumban',
    'peoples.bamoun.h3': 'Art sculptural et masques traditionnels',
    'peoples.bamoun.h4': 'Riches traditions musicales',
    'peoples.nso.name': 'Les Nso\'',
    'peoples.nso.region': 'Région du Nord-Ouest, Cameroun',
    'peoples.nso.desc': 'Descendants du peuple Tikar, ils ont préservé une identité culturelle et sociale forte malgré les migrations et les bouleversements historiques.',
    'peoples.nso.long_desc': 'Les Nso\' sont les descendants directs du peuple Tikar, qui a migré vers les hauts plateaux du nord-ouest du Cameroun. Leur organisation sociale sophistiquée et leurs institutions traditionnelles ont survécu aux bouleversements de l\'histoire coloniale. La chefferie Nso\' reste l\'une des plus influentes de la région.',
    'peoples.nso.h1': 'Puissante chefferie traditionnelle',
    'peoples.nso.h2': 'Organisation sociale structurée',
    'peoples.nso.h3': 'Traditions orales préservées',
    'peoples.nso.h4': 'Langue Lamnso\' vivante',
    'peoples.bafia.name': 'Les Bafia',
    'peoples.bafia.region': 'Région du Mbam, Cameroun',
    'peoples.bafia.desc': 'Un peuple bantou aux traditions et structures sociales profondément enracinées, gardiens du savoir ancestral.',
    'peoples.bafia.long_desc': 'Les Bafia sont un peuple bantou installé dans la région du Mbam. Leurs traditions et structures sociales sont profondément enracinées dans un savoir ancestral transmis de génération en génération. Leur culture riche comprend des rituels, des danses et une cosmogonie unique qui témoignent de leur histoire millénaire.',
    'peoples.bafia.h1': 'Structures sociales ancestrales',
    'peoples.bafia.h2': 'Danses et rituels traditionnels',
    'peoples.bafia.h3': 'Artisanat et savoir-faire',
    'peoples.bafia.h4': 'Cosmogonie et spiritualité',
    'peoples.unity_title': 'Unis par l\'Histoire, la Culture et la',
    'peoples.unity_highlight': 'Fraternité',
    'peoples.unity_text': 'Ces trois peuples partagent des liens historiques, linguistiques et culturels profonds. L\'International Mandjara Heritage œuvre pour renforcer ces liens et préserver ce patrimoine commun pour les générations futures.',
    'peoples.unity_badge': 'Trois peuples, une même famille',

    // Values Page
    'values.badge': 'Nos Valeurs Fondamentales',
    'values.title': 'Les Principes Qui',
    'values.title_highlight': 'Nous Guident',
    'values.subtitle': 'Nos valeurs sont le fondement de chaque décision, comportement et action de l\'International Mandjara Heritage.',
    'values.creativity': 'Créativité',
    'values.creativity_desc': 'Les solutions émergent de l\'innovation et de la production d\'idées nouvelles.',
    'values.creativity_long': 'Nous croyons que l\'innovation culturelle est le moteur du progrès. La créativité nous permet de trouver des solutions uniques aux défis contemporains tout en honorant nos traditions ancestrales.',
    'values.dialogue': 'Dialogue',
    'values.dialogue_desc': 'L\'écoute, le respect et la coopération sont au cœur des relations humaines.',
    'values.dialogue_long': 'Le dialogue interculturel est la base de notre action. Nous favorisons les échanges respectueux entre les communautés, les générations et les cultures pour construire des ponts durables.',
    'values.solidarity': 'Solidarité',
    'values.solidarity_desc': 'La culture et l\'humanité étant interdépendantes, il est de notre devoir de préserver la cohésion culturelle.',
    'values.solidarity_long': 'La solidarité communautaire est notre force. Ensemble, nous soutenons les membres de nos communautés et travaillons pour le bien-être collectif, ici et dans nos pays d\'origine.',
    'values.transparency': 'Transparence',
    'values.transparency_desc': 'Les informations relatives aux activités de l\'International Mandjara Heritage sont rendues accessibles au public.',
    'values.transparency_long': 'Nous nous engageons à une gouvernance transparente et responsable. Chaque action, chaque décision est documentée et partagée avec notre communauté.',
    'values.sustainability': 'Durabilité Culturelle',
    'values.sustainability_desc': 'En cohérence avec les trois autres piliers du développement durable, la culture est le ciment qui unit identité, progrès et environnement.',
    'values.sustainability_long': 'La culture n\'est pas un luxe mais une nécessité. Elle est le quatrième pilier du développement durable, indissociable des dimensions économique, sociale et environnementale.',
    'values.pillars_title': 'Les Quatre Piliers du',
    'values.pillars_highlight': 'Développement Durable',
    'values.pillars_subtitle': 'L\'International Mandjara Heritage reconnaît la culture comme le quatrième pilier indispensable au développement durable, aux côtés des dimensions économique, sociale et environnementale.',
    'values.pillar.economic': 'Économique',
    'values.pillar.economic_desc': 'Développement économique responsable et inclusif',
    'values.pillar.social': 'Social',
    'values.pillar.social_desc': 'Justice sociale et équité pour tous',
    'values.pillar.environmental': 'Environnemental',
    'values.pillar.environmental_desc': 'Protection de notre planète et de ses ressources',
    'values.pillar.cultural': 'Culturel',
    'values.pillar.cultural_desc': 'Préservation et transmission du patrimoine',
    'values.quote': 'La culture n\'est pas un supplément d\'âme, mais le ciment qui unit identité, progrès et environnement dans une vision holistique du développement intégrant durabilité, paix et bien-être des sociétés.',
    'values.quote_author': 'UNESCO (2005)',

    // Mission Page
    'mission.badge': 'Notre Mission & Vision',
    'mission.title': 'Promouvoir, Préserver,',
    'mission.title_highlight': 'Transmettre',
    'mission.subtitle': 'Découvrez notre engagement envers la préservation et la transmission du patrimoine culturel, historique et social du peuple Mandjara.',
    'mission.label': 'Notre Mission',
    'mission.heading': 'Un Engagement',
    'mission.heading_highlight': 'Concret',
    'mission.text': 'L\'International Mandjara Heritage a pour mission de promouvoir, préserver et transmettre le patrimoine culturel, historique et social du peuple Mandjara (Bamoun, Bafia, Nso\') et des communautés apparentées.',
    'mission.point.research': 'Recherche & Documentation',
    'mission.point.research_text': 'Favoriser la recherche, la documentation et la valorisation du patrimoine matériel et immatériel Mandjara',
    'mission.point.links': 'Liens Intergénérationnels',
    'mission.point.links_text': 'Renforcer les liens entre les générations et les diasporas issues de ces communautés',
    'mission.point.collab': 'Collaboration Internationale',
    'mission.point.collab_text': 'Collaborer avec des institutions canadiennes et internationales pour promouvoir la diversité',
    'mission.point.education': 'Activités Éducatives',
    'mission.point.education_text': 'Organiser des activités éducatives et culturelles au Canada et à l\'international',
    'mission.vision_label': 'Notre Vision',
    'mission.vision_heading': 'Un Pont Entre',
    'mission.vision_heading_highlight': 'Mémoire et Avenir',
    'mission.vision_text': 'Une société où l\'histoire, la culture et la connaissance du peuple Mandjara sont reconnues comme piliers du développement durable, au même titre que l\'économie, la justice sociale et la protection de l\'environnement.',
    'mission.vision.sustainability': 'Durabilité Culturelle',
    'mission.vision.international': 'Rayonnement International',
    'mission.vision_quote': '"Les enjeux culturels, économiques et sociaux sont étroitement liés et doivent être traités de manière globale, afin que l\'héritage de nos ancêtres continue d\'être le symbole de notre identité."',
    'mission.objectives_title': 'Nos',
    'mission.objectives_highlight': 'Objectifs',
    'mission.objectives_subtitle': 'Des actions concrètes pour réaliser notre vision d\'un avenir où la culture est au cœur du développement durable.',
    'mission.obj.education': 'Éducation Culturelle',
    'mission.obj.education_desc': 'Programmes éducatifs pour transmettre le savoir ancestral aux nouvelles générations.',
    'mission.obj.partnerships': 'Partenariats Stratégiques',
    'mission.obj.partnerships_desc': 'Développer des collaborations avec des institutions académiques et culturelles.',
    'mission.obj.social': 'Actions Sociales',
    'mission.obj.social_desc': 'Soutenir les initiatives communautaires et le bien-être des membres.',
    'mission.obj.preservation': 'Préservation Patrimoniale',
    'mission.obj.preservation_desc': 'Documenter et préserver les artefacts, traditions et pratiques culturelles.',

    // Contact Page
    'contact.badge': 'Contactez-nous',
    'contact.title': 'Rejoignez',
    'contact.title_highlight': 'Notre Communauté',
    'contact.subtitle': 'Vous souhaitez contribuer à la préservation du patrimoine Mandjara ? Contactez-nous pour faire partie de cette belle aventure.',
    'contact.info_title': 'Informations de Contact',
    'contact.info_text': 'N\'hésitez pas à nous contacter pour toute question concernant notre organisation, nos projets ou comment vous pouvez contribuer.',
    'contact.email': 'Email',
    'contact.location': 'Localisation',
    'contact.phone': 'Téléphone',
    'contact.presence': 'Présence',
    'contact.newsletter_title': 'Restez Informé',
    'contact.newsletter_text': 'Inscrivez-vous à notre newsletter pour recevoir les dernières actualités.',
    'contact.newsletter_placeholder': 'Votre email',
    'contact.form_title': 'Envoyez-nous un Message',
    'contact.form_text': 'Remplissez le formulaire ci-dessous et nous vous répondrons dans les plus brefs délais.',
    'contact.form.name': 'Nom complet *',
    'contact.form.name_placeholder': 'Votre nom',
    'contact.form.email': 'Email *',
    'contact.form.email_placeholder': 'votre@email.com',
    'contact.form.subject': 'Sujet',
    'contact.form.subject_placeholder': 'Comment pouvons-nous vous aider ?',
    'contact.form.message': 'Message *',
    'contact.form.message_placeholder': 'Décrivez votre demande en détail...',
    'contact.form.send': 'Envoyer le Message',
    'contact.form.success_title': 'Message envoyé !',
    'contact.form.success_desc': 'Nous vous répondrons dans les plus brefs délais.',
    'contact.cta_title': 'Ensemble, Préservons Notre',
    'contact.cta_highlight': 'Héritage',
    'contact.cta_text': 'Que vous soyez membre de la diaspora Mandjara, chercheur, partenaire institutionnel ou simplement passionné par la préservation culturelle, votre contribution compte.',
    'contact.cta.member': 'Devenir Membre',
    'contact.cta.donate': 'Faire un Don',

    // Donation Page
    'donation.badge': 'Soutenez Notre Mission',
    'donation.title': 'Faites un',
    'donation.title_highlight': 'Don',
    'donation.subtitle': 'Votre générosité nous permet de préserver et transmettre le patrimoine culturel des peuples Bamoun, Nso\' et Bafia aux générations futures.',
    'donation.choose_badge': 'Choisissez Votre Contribution',
    'donation.levels_title': 'Niveaux de',
    'donation.levels_highlight': 'Donation',
    'donation.levels_subtitle': 'Chaque contribution, quelle que soit sa taille, fait une différence significative dans notre mission de préservation culturelle.',
    'donation.opt1': 'Ami du Patrimoine',
    'donation.opt1_desc': 'Contribuez à la préservation de notre héritage culturel',
    'donation.opt2': 'Gardien de la Culture',
    'donation.opt2_desc': 'Soutenez nos programmes éducatifs et culturels',
    'donation.opt3': 'Ambassadeur Mandjara',
    'donation.opt3_desc': 'Participez activement à nos projets communautaires',
    'donation.opt4': 'Mécène du Patrimoine',
    'donation.opt4_desc': 'Devenez un pilier de notre mission de préservation',
    'donation.give': 'Donner',
    'donation.custom_title': 'Montant Personnalisé',
    'donation.custom_text': 'Vous souhaitez contribuer avec un montant différent ? Contactez-nous directement.',
    'donation.custom_cta': 'Nous Contacter',
    'donation.impact_badge': 'Votre Impact',
    'donation.impact_title': 'Comment Votre Don',
    'donation.impact_highlight': 'Fait la Différence',
    'donation.impact1': 'Préservation Culturelle',
    'donation.impact1_desc': 'Documentation et archivage des traditions orales, artisanales et musicales des peuples Bamoun, Nso\' et Bafia.',
    'donation.impact2': 'Éducation & Transmission',
    'donation.impact2_desc': 'Programmes éducatifs pour transmettre notre héritage aux jeunes générations.',
    'donation.impact3': 'Événements Culturels',
    'donation.impact3_desc': 'Organisation de festivals, expositions et rencontres culturelles.',
    'donation.payment_title': 'Modalités de',
    'donation.payment_highlight': 'Paiement',
    'donation.payment_text': 'Pour effectuer votre don, veuillez nous contacter directement. Nous acceptons les virements bancaires et autres modes de paiement sécurisés.',
    'donation.payment_cta': 'Contacter pour Donner',

    // Footer
    'footer.description': 'Préserver et transmettre le patrimoine culturel, historique et social des peuples Bamoun, Nso\' et Bafia pour les générations futures.',
    'footer.organisation': 'Organisation',
    'footer.resources': 'Ressources',
    'footer.legal': 'Légal',
    'footer.publications': 'Publications',
    'footer.events': 'Événements',
    'footer.gallery': 'Galerie',
    'footer.partners': 'Partenaires',
    'footer.legal_notices': 'Mentions légales',
    'footer.privacy': 'Politique de confidentialité',
    'footer.terms': 'Conditions d\'utilisation',
    'footer.rights': 'Tous droits réservés.',
    'footer.tagline': 'Préservons notre héritage ensemble 🌍',

    // Team Pages
    'team.badge': 'Notre Équipe',
    'team.hero_title': 'Leadership &',
    'team.hero_highlight': 'Gouvernance',
    'team.hero_subtitle': 'Des leaders engagés au service du patrimoine Mandjara, unis par une vision commune de préservation et de transmission culturelle.',
    'team.section_subtitle': 'Des leaders engagés au service du patrimoine Mandjara',
    'team.coming_soon': 'Cette section sera complétée prochainement',

    // Team Categories
    'team.cat.parrains': 'Haut Patronage Royal et Traditionnel',
    'team.cat.parrains_sub': 'Personnalités de marque soutenant notre mission',
    'team.cat.honneur': 'Membres d\'honneur',
    'team.cat.honneur_sub': 'Reconnus pour leur contribution exceptionnelle',
    'team.cat.conseil': 'Conseil d\'Administration',
    'team.cat.conseil_sub': 'Direction stratégique et gouvernance de l\'organisation',
    'team.cat.bureau': 'Bureau Exécutif',
    'team.cat.bureau_sub': 'Coordination opérationnelle des activités',
    'team.cat.representants': 'Représentation nationale',
    'team.cat.representants_sub': 'Ambassadeurs du patrimoine Mandjara à travers le monde',
    'team.cat.sages': 'Comité des Sages',
    'team.cat.sages_sub': 'Gardiennes et gardiens de la sagesse et de la tradition',

    // Parrains Page
    'team.parrains.coming_title': 'Section à venir',
    'team.parrains.coming_desc': 'Les parrains de l\'International Mandjara Heritage seront présentés prochainement.',

    // Publications Page
    'publications.badge': 'Recherche & Documentation',
    'publications.title': 'Nos',
    'publications.title_highlight': 'Publications',
    'publications.subtitle': 'Découvrez les travaux de recherche et publications académiques liés au patrimoine et à la communauté Mandjara.',
    'publications.type_thesis': 'Thèse de doctorat',
    'publications.thesis_desc': 'Cette thèse examine les politiques publiques, programmes et projets sensibles au genre dans la communauté Mandjara au Cameroun. Elle analyse les processus de construction des identités masculines et féminines, la mobilisation féminine et les phénomènes sociopolitiques à travers le prisme du genre.',
    'publications.read': 'Lire le document',
    'publications.download': 'Télécharger',
    'publications.events_title': 'Événements',
    'publications.nguoun_desc': 'Le Nguoun 2024, grande fête traditionnelle du peuple Bamoun.',
    'publications.partners_title': 'Partenaires',
    'publications.coming_soon': 'Information à venir',

    // Events Page
    'events.badge': 'Événements & Partenaires',
    'events.title': 'Nos',
    'events.title_highlight': 'Événements',
    'events.subtitle': 'Découvrez nos événements culturels, partenariats et activités communautaires.',

    // Nguoun Page
    'nguoun.badge': 'Événement Culturel',
    'nguoun.subtitle': 'La grande fête traditionnelle biennale du peuple Bamoun à Foumban, Cameroun.',
    'nguoun.about_title': 'Qu\'est-ce que le Nguoun ?',
    'nguoun.about_text': 'Le Nguoun est la plus grande fête traditionnelle du peuple Bamoun. Cet événement biennal célèbre la culture, l\'histoire et les traditions du royaume Bamoun. Il rassemble la communauté Bamoun du monde entier autour de cérémonies rituelles, de danses traditionnelles, de musiques et de festivités qui perpétuent un héritage culturel riche et ancestral.',
    'nguoun.date_label': 'Date',
    'nguoun.location_label': 'Lieu',
    'nguoun.people_label': 'Peuple',
    'nguoun.people_value': 'Peuple Bamoun',
    'nguoun.significance_title': 'Importance culturelle',
    'nguoun.significance_text': 'Le Nguoun représente un moment privilégié de communion et de retrouvailles pour le peuple Bamoun. C\'est l\'occasion de renouveler les liens communautaires, de transmettre les savoirs ancestraux aux jeunes générations et de célébrer l\'identité culturelle Bamoun dans toute sa richesse et sa diversité.',
    'nguoun.videos_title': 'Vidéos du Nguoun Septembre 2024',

    'publications.contribute_title': 'Contribuez à Notre Documentation',
    'publications.contribute_text': 'Vous êtes chercheur, universitaire ou auteur d\'un travail lié au patrimoine Mandjara ? Partagez votre publication avec nous pour enrichir notre collection.',
    'publications.contribute_cta': 'Nous Contacter',

    // Galerie Page
    'galerie.badge': 'Photos & Médias',
    'galerie.title': 'Notre',
    'galerie.title_highlight': 'Galerie',
    'galerie.subtitle': 'Découvrez en images les moments forts de notre communauté et de nos événements.',

    // Partenaires Page
    'partenaires.badge': 'Nos Partenaires',
    'partenaires.title': 'Nos',
    'partenaires.title_highlight': 'Partenaires',
    'partenaires.subtitle': 'Les organisations et institutions qui soutiennent notre mission de préservation du patrimoine.',
  },

  en: {
    // Nav
    'nav.home': 'Home',
    'nav.history': 'Our History',
    'nav.peoples': 'Peoples',
    'nav.mission': 'Mission & Vision',
    'nav.values': 'Values',
    'nav.contact': 'Contact',
    'nav.team': 'Our Team',
    'nav.donate': 'Donate',
    'nav.team.parrains': 'Royal and Traditional High Patronage',
    'nav.team.membres_honneur': 'Honorary Members',
    'nav.team.conseil': 'Board of Directors',
    'nav.team.bureau': 'Executive Board',
    'nav.team.representants': 'National Representatives',
    'nav.team.comite': 'Council of Elders',
    'nav.publications': 'Publications',
    'nav.evenements': 'Events',
    'nav.ressources': 'Resources',
    'nav.galerie': 'Gallery',
    'nav.partenaires': 'Partners',

    // Hero
    'hero.badge': 'Heritage • Culture • Legacy',
    'hero.title1': 'International',
    'hero.title2': 'Mandjara',
    'hero.title3': 'Heritage',
    'hero.subtitle': 'Preserving and transmitting the cultural, historical and social heritage of the',
    'hero.cta1': 'Discover Our Mission',
    'hero.cta2': 'Learn More',
    'hero.scroll': 'Discover',

    // Index
    'index.explore_badge': 'Explore Our Heritage',
    'index.explore_title': 'Discover Our',
    'index.explore_title_highlight': 'Organization',
    'index.explore_subtitle': 'Navigate through the different sections to learn more about our mission, values and cultural commitment.',
    'index.card.history': 'Our History',
    'index.card.history_desc': 'Discover the deep roots of International Mandjara Heritage and its anchoring in the Mandjara people\'s culture.',
    'index.card.peoples': 'The Three Peoples',
    'index.card.peoples_desc': 'Explore the cultural heritage of the Bamoun, Nso\' and Bafia, the three great founding peoples.',
    'index.card.mission': 'Our Mission',
    'index.card.mission_desc': 'Promote, preserve and transmit cultural heritage for future generations.',
    'index.card.values': 'Our Values',
    'index.card.values_desc': 'The fundamental principles that guide every decision and action of our organization.',
    'index.learn_more': 'Learn more',
    'index.team_title': 'Our Team',
    'index.team_desc': 'Meet the committed leaders who carry the vision of International Mandjara Heritage.',
    'index.team_link': 'Discover the team',
    'index.join_title': 'Join Us',
    'index.join_desc': 'Contact us to contribute to the preservation of our cultural heritage.',
    'index.join_link': 'Contact us',

    // Context Page
    'context.badge': 'Context & Origins',
    'context.title': 'A',
    'context.title_highlight': 'Millennial Heritage',
    'context.subtitle': 'Discover the deep roots of International Mandjara Heritage and its anchoring in the history and culture of the Mandjara people.',
    'context.roots_title': 'The Roots of Our',
    'context.roots_highlight': 'Commitment',
    'context.roots_p1': 'International Mandjara Heritage finds its roots in the history and culture of the Mandjara people, a Central African ethnic group that has shaped its identity, language and traditions through the centuries.',
    'context.roots_p2': 'It draws inspiration from this heritage to promote social, cultural and educational development while respecting local traditions, within a contemporary approach to sustainable development based on four pillars: economic, social, environmental and cultural.',
    'context.roots_p3': 'This approach aligns with the UNESCO Universal Declaration on Cultural Diversity (2001) and the Convention on the Diversity of Cultural Expressions (2005).',
    'context.quote': 'Culture is essential to sustainability, peace and the well-being of societies.',
    'context.quote_author': 'UNESCO, 2005',
    'context.timeline_title': 'Our',
    'context.timeline_highlight': 'History',
    'context.timeline.19th': '19th Century',
    'context.timeline.19th_title': 'Invention of Shu-Mom Writing',
    'context.timeline.19th_desc': 'King Njoya creates a unique writing system for the Bamoun people.',
    'context.timeline.2001': '2001',
    'context.timeline.2001_title': 'UNESCO Declaration',
    'context.timeline.2001_desc': 'Universal Declaration on Cultural Diversity.',
    'context.timeline.2005': '2005',
    'context.timeline.2005_title': 'UNESCO Convention',
    'context.timeline.2005_desc': 'Convention on the Diversity of Cultural Expressions.',
    'context.timeline.today': 'Today',
    'context.timeline.today_title': 'International Mandjara Heritage',
    'context.timeline.today_desc': 'Cultural continuity and sustainable development.',
    'context.feature.ancestors': 'Respect for Ancestors',
    'context.feature.ancestors_desc': 'Honoring the memory and teachings of those who shaped our identity through the centuries.',
    'context.feature.solidarity': 'Community Solidarity',
    'context.feature.solidarity_desc': 'Strengthening bonds between generations and diasporas from our communities.',
    'context.feature.knowledge': 'Knowledge Transmission',
    'context.feature.knowledge_desc': 'Preserving and sharing tangible and intangible heritage for future generations.',

    // Peoples Page
    'peoples.badge': 'The Three Founding Peoples',
    'peoples.title': 'The',
    'peoples.title_highlight': 'Mandjara Peoples',
    'peoples.subtitle': 'Discover the three great peoples of Cameroon that form the heart of International Mandjara Heritage: the Bamoun, the Nso\' and the Bafia.',
    'peoples.founding': 'Founding People',
    'peoples.bamoun.name': 'The Bamoun',
    'peoples.bamoun.region': 'Noun Region, Cameroon',
    'peoples.bamoun.desc': 'Exceptional artistic and cultural heritage, including the writing system invented by King Njoya at the end of the 19th century.',
    'peoples.bamoun.long_desc': 'The Bamoun people are recognised worldwide for their exceptional artistic and cultural heritage. King Njoya, an iconic figure, invented a unique writing system called Shu-Mom at the end of the 19th century, demonstrating the creative genius of this civilisation. The Palace of the Bamoun Kings in Foumban remains a living testimony to this cultural greatness.',
    'peoples.bamoun.h1': 'Shu-Mom script invented by King Njoya',
    'peoples.bamoun.h2': 'Royal Palace of Foumban',
    'peoples.bamoun.h3': 'Sculptural art and traditional masks',
    'peoples.bamoun.h4': 'Rich musical traditions',
    'peoples.nso.name': 'The Nso\'',
    'peoples.nso.region': 'North-West Region, Cameroon',
    'peoples.nso.desc': 'Descendants of the Tikar people, they have preserved a strong cultural and social identity despite migrations and historical upheavals.',
    'peoples.nso.long_desc': 'The Nso\' are the direct descendants of the Tikar people, who migrated to the high plateaus of north-western Cameroon. Their sophisticated social organisation and traditional institutions have survived the upheavals of colonial history. The Nso\' chiefdom remains one of the most influential in the region.',
    'peoples.nso.h1': 'Powerful traditional chiefdom',
    'peoples.nso.h2': 'Structured social organisation',
    'peoples.nso.h3': 'Preserved oral traditions',
    'peoples.nso.h4': 'Living Lamnso\' language',
    'peoples.bafia.name': 'The Bafia',
    'peoples.bafia.region': 'Mbam Region, Cameroon',
    'peoples.bafia.desc': 'A Bantu people with deeply rooted traditions and social structures, guardians of ancestral knowledge.',
    'peoples.bafia.long_desc': 'The Bafia are a Bantu people settled in the Mbam region. Their traditions and social structures are deeply rooted in ancestral knowledge passed down from generation to generation. Their rich culture includes rituals, dances and a unique cosmogony that bear witness to their thousand-year history.',
    'peoples.bafia.h1': 'Ancestral social structures',
    'peoples.bafia.h2': 'Traditional dances and rituals',
    'peoples.bafia.h3': 'Craftsmanship and expertise',
    'peoples.bafia.h4': 'Cosmogony and spirituality',
    'peoples.unity_title': 'United by History, Culture and',
    'peoples.unity_highlight': 'Brotherhood',
    'peoples.unity_text': 'These three peoples share deep historical, linguistic and cultural bonds. International Mandjara Heritage works to strengthen these ties and preserve this common heritage for future generations.',
    'peoples.unity_badge': 'Three peoples, one family',

    // Values Page
    'values.badge': 'Our Core Values',
    'values.title': 'The Principles That',
    'values.title_highlight': 'Guide Us',
    'values.subtitle': 'Our values are the foundation of every decision, behavior and action of International Mandjara Heritage.',
    'values.creativity': 'Creativity',
    'values.creativity_desc': 'Solutions emerge from innovation and the production of new ideas.',
    'values.creativity_long': 'We believe that cultural innovation drives progress. Creativity allows us to find unique solutions to contemporary challenges while honoring our ancestral traditions.',
    'values.dialogue': 'Dialogue',
    'values.dialogue_desc': 'Listening, respect and cooperation are at the heart of human relationships.',
    'values.dialogue_long': 'Intercultural dialogue is the foundation of our action. We foster respectful exchanges between communities, generations and cultures to build lasting bridges.',
    'values.solidarity': 'Solidarity',
    'values.solidarity_desc': 'As culture and humanity are interdependent, it is our duty to preserve cultural cohesion.',
    'values.solidarity_long': 'Community solidarity is our strength. Together, we support the members of our communities and work for collective well-being, both here and in our countries of origin.',
    'values.transparency': 'Transparency',
    'values.transparency_desc': 'Information relating to the activities of International Mandjara Heritage is made accessible to the public.',
    'values.transparency_long': 'We are committed to transparent and responsible governance. Every action, every decision is documented and shared with our community.',
    'values.sustainability': 'Cultural Sustainability',
    'values.sustainability_desc': 'In line with the three other pillars of sustainable development, culture is the cement that unites identity, progress and environment.',
    'values.sustainability_long': 'Culture is not a luxury but a necessity. It is the fourth pillar of sustainable development, inseparable from the economic, social and environmental dimensions.',
    'values.pillars_title': 'The Four Pillars of',
    'values.pillars_highlight': 'Sustainable Development',
    'values.pillars_subtitle': 'International Mandjara Heritage recognizes culture as the essential fourth pillar of sustainable development, alongside the economic, social and environmental dimensions.',
    'values.pillar.economic': 'Economic',
    'values.pillar.economic_desc': 'Responsible and inclusive economic development',
    'values.pillar.social': 'Social',
    'values.pillar.social_desc': 'Social justice and equity for all',
    'values.pillar.environmental': 'Environmental',
    'values.pillar.environmental_desc': 'Protecting our planet and its resources',
    'values.pillar.cultural': 'Cultural',
    'values.pillar.cultural_desc': 'Preservation and transmission of heritage',
    'values.quote': 'Culture is not a supplement to the soul, but the cement that unites identity, progress and environment in a holistic vision of development integrating sustainability, peace and the well-being of societies.',
    'values.quote_author': 'UNESCO (2005)',

    // Mission Page
    'mission.badge': 'Our Mission & Vision',
    'mission.title': 'Promote, Preserve,',
    'mission.title_highlight': 'Transmit',
    'mission.subtitle': 'Discover our commitment to the preservation and transmission of the cultural, historical and social heritage of the Mandjara people.',
    'mission.label': 'Our Mission',
    'mission.heading': 'A Concrete',
    'mission.heading_highlight': 'Commitment',
    'mission.text': 'International Mandjara Heritage\'s mission is to promote, preserve and transmit the cultural, historical and social heritage of the Mandjara people (Bamoun, Bafia, Nso\') and related communities.',
    'mission.point.research': 'Research & Documentation',
    'mission.point.research_text': 'Foster research, documentation and valorization of Mandjara tangible and intangible heritage',
    'mission.point.links': 'Intergenerational Links',
    'mission.point.links_text': 'Strengthen bonds between generations and diasporas from these communities',
    'mission.point.collab': 'International Collaboration',
    'mission.point.collab_text': 'Collaborate with Canadian and international institutions to promote diversity',
    'mission.point.education': 'Educational Activities',
    'mission.point.education_text': 'Organize educational and cultural activities in Canada and internationally',
    'mission.vision_label': 'Our Vision',
    'mission.vision_heading': 'A Bridge Between',
    'mission.vision_heading_highlight': 'Memory and Future',
    'mission.vision_text': 'A society where the history, culture and knowledge of the Mandjara people are recognized as pillars of sustainable development, equal to the economy, social justice and environmental protection.',
    'mission.vision.sustainability': 'Cultural Sustainability',
    'mission.vision.international': 'International Outreach',
    'mission.vision_quote': '"Cultural, economic and social issues are closely linked and must be addressed holistically, so that the heritage of our ancestors continues to be the symbol of our identity."',
    'mission.objectives_title': 'Our',
    'mission.objectives_highlight': 'Objectives',
    'mission.objectives_subtitle': 'Concrete actions to achieve our vision of a future where culture is at the heart of sustainable development.',
    'mission.obj.education': 'Cultural Education',
    'mission.obj.education_desc': 'Educational programs to transmit ancestral knowledge to new generations.',
    'mission.obj.partnerships': 'Strategic Partnerships',
    'mission.obj.partnerships_desc': 'Develop collaborations with academic and cultural institutions.',
    'mission.obj.social': 'Social Actions',
    'mission.obj.social_desc': 'Support community initiatives and member well-being.',
    'mission.obj.preservation': 'Heritage Preservation',
    'mission.obj.preservation_desc': 'Document and preserve artifacts, traditions and cultural practices.',

    // Contact Page
    'contact.badge': 'Contact Us',
    'contact.title': 'Join',
    'contact.title_highlight': 'Our Community',
    'contact.subtitle': 'Would you like to contribute to the preservation of Mandjara heritage? Contact us to be part of this wonderful adventure.',
    'contact.info_title': 'Contact Information',
    'contact.info_text': 'Feel free to contact us for any questions about our organization, our projects or how you can contribute.',
    'contact.email': 'Email',
    'contact.location': 'Location',
    'contact.phone': 'Phone',
    'contact.presence': 'Presence',
    'contact.newsletter_title': 'Stay Informed',
    'contact.newsletter_text': 'Subscribe to our newsletter to receive the latest news.',
    'contact.newsletter_placeholder': 'Your email',
    'contact.form_title': 'Send Us a Message',
    'contact.form_text': 'Fill in the form below and we will respond as soon as possible.',
    'contact.form.name': 'Full name *',
    'contact.form.name_placeholder': 'Your name',
    'contact.form.email': 'Email *',
    'contact.form.email_placeholder': 'your@email.com',
    'contact.form.subject': 'Subject',
    'contact.form.subject_placeholder': 'How can we help you?',
    'contact.form.message': 'Message *',
    'contact.form.message_placeholder': 'Describe your request in detail...',
    'contact.form.send': 'Send Message',
    'contact.form.success_title': 'Message sent!',
    'contact.form.success_desc': 'We will respond as soon as possible.',
    'contact.cta_title': 'Together, Let\'s Preserve Our',
    'contact.cta_highlight': 'Heritage',
    'contact.cta_text': 'Whether you are a member of the Mandjara diaspora, a researcher, an institutional partner or simply passionate about cultural preservation, your contribution matters.',
    'contact.cta.member': 'Become a Member',
    'contact.cta.donate': 'Make a Donation',

    // Donation Page
    'donation.badge': 'Support Our Mission',
    'donation.title': 'Make a',
    'donation.title_highlight': 'Donation',
    'donation.subtitle': 'Your generosity allows us to preserve and transmit the cultural heritage of the Bamoun, Nso\' and Bafia peoples for future generations.',
    'donation.choose_badge': 'Choose Your Contribution',
    'donation.levels_title': 'Donation',
    'donation.levels_highlight': 'Levels',
    'donation.levels_subtitle': 'Every contribution, regardless of size, makes a significant difference in our cultural preservation mission.',
    'donation.opt1': 'Heritage Friend',
    'donation.opt1_desc': 'Contribute to the preservation of our cultural heritage',
    'donation.opt2': 'Culture Guardian',
    'donation.opt2_desc': 'Support our educational and cultural programs',
    'donation.opt3': 'Mandjara Ambassador',
    'donation.opt3_desc': 'Actively participate in our community projects',
    'donation.opt4': 'Heritage Patron',
    'donation.opt4_desc': 'Become a pillar of our preservation mission',
    'donation.give': 'Give',
    'donation.custom_title': 'Custom Amount',
    'donation.custom_text': 'Would you like to contribute a different amount? Contact us directly.',
    'donation.custom_cta': 'Contact Us',
    'donation.impact_badge': 'Your Impact',
    'donation.impact_title': 'How Your Donation',
    'donation.impact_highlight': 'Makes a Difference',
    'donation.impact1': 'Cultural Preservation',
    'donation.impact1_desc': 'Documentation and archiving of oral, craft and musical traditions of the Bamoun, Nso\' and Bafia peoples.',
    'donation.impact2': 'Education & Transmission',
    'donation.impact2_desc': 'Educational programs to transmit our heritage to younger generations.',
    'donation.impact3': 'Cultural Events',
    'donation.impact3_desc': 'Organization of festivals, exhibitions and cultural gatherings.',
    'donation.payment_title': 'Payment',
    'donation.payment_highlight': 'Methods',
    'donation.payment_text': 'To make your donation, please contact us directly. We accept bank transfers and other secure payment methods.',
    'donation.payment_cta': 'Contact to Donate',

    // Footer
    'footer.description': 'Preserving and transmitting the cultural, historical and social heritage of the Bamoun, Nso\' and Bafia peoples for future generations.',
    'footer.organisation': 'Organization',
    'footer.resources': 'Resources',
    'footer.legal': 'Legal',
    'footer.publications': 'Publications',
    'footer.events': 'Events',
    'footer.gallery': 'Gallery',
    'footer.partners': 'Partners',
    'footer.legal_notices': 'Legal Notices',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Use',
    'footer.rights': 'All rights reserved.',
    'footer.tagline': 'Let\'s preserve our heritage together 🌍',

    // Team Pages
    'team.badge': 'Our Team',
    'team.hero_title': 'Leadership &',
    'team.hero_highlight': 'Governance',
    'team.hero_subtitle': 'Committed leaders serving the Mandjara heritage, united by a shared vision of preservation and cultural transmission.',
    'team.section_subtitle': 'Committed leaders serving the Mandjara heritage',
    'team.coming_soon': 'This section will be completed soon',

    // Team Categories
    'team.cat.parrains': 'Royal and Traditional High Patronage',
    'team.cat.parrains_sub': 'Distinguished figures supporting our mission',
    'team.cat.honneur': 'Honorary Members',
    'team.cat.honneur_sub': 'Recognized for their outstanding contribution',
    'team.cat.conseil': 'Board of Directors',
    'team.cat.conseil_sub': 'Strategic direction and governance of the organization',
    'team.cat.bureau': 'Executive Board',
    'team.cat.bureau_sub': 'Operational coordination of activities',
    'team.cat.representants': 'National Representatives',
    'team.cat.representants_sub': 'Ambassadors of Mandjara heritage around the world',
    'team.cat.sages': 'Council of Elders',
    'team.cat.sages_sub': 'Guardians of wisdom and tradition',

    // Parrains Page
    'team.parrains.coming_title': 'Coming Soon',
    'team.parrains.coming_desc': 'The patrons of International Mandjara Heritage will be presented soon.',

    // Publications Page
    'publications.badge': 'Research & Documentation',
    'publications.title': 'Our',
    'publications.title_highlight': 'Publications',
    'publications.subtitle': 'Discover research works and academic publications related to the Mandjara heritage and community.',
    'publications.type_thesis': 'Doctoral thesis',
    'publications.thesis_desc': 'This thesis examines gender-sensitive public policies, programs and projects in the Mandjara community in Cameroon. It analyses the processes of constructing masculine and feminine identities, female mobilisation and sociopolitical phenomena through the lens of gender.',
    'publications.read': 'Read document',
    'publications.download': 'Download',
    'publications.events_title': 'Events',
    'publications.nguoun_desc': 'The Nguoun 2024, grand traditional festival of the Bamoun people.',
    'publications.partners_title': 'Partners',
    'publications.coming_soon': 'Information coming soon',
    'publications.contribute_title': 'Contribute to Our Documentation',
    'publications.contribute_text': 'Are you a researcher, academic or author of work related to the Mandjara heritage? Share your publication with us to enrich our collection.',
    'publications.contribute_cta': 'Contact Us',

    // Events Page
    'events.badge': 'Events & Partners',
    'events.title': 'Our',
    'events.title_highlight': 'Events',
    'events.subtitle': 'Discover our cultural events, partnerships and community activities.',

    // Nguoun Page
    'nguoun.badge': 'Cultural Event',
    'nguoun.subtitle': 'The grand biennial traditional festival of the Bamoun people in Foumban, Cameroon.',
    'nguoun.about_title': 'What is the Nguoun?',
    'nguoun.about_text': 'The Nguoun is the greatest traditional festival of the Bamoun people. This biennial event celebrates the culture, history and traditions of the Bamoun kingdom. It brings together the Bamoun community from around the world for ritual ceremonies, traditional dances, music and festivities that perpetuate a rich and ancestral cultural heritage.',
    'nguoun.date_label': 'Date',
    'nguoun.location_label': 'Location',
    'nguoun.people_label': 'People',
    'nguoun.people_value': 'Bamoun People',
    'nguoun.significance_title': 'Cultural Significance',
    'nguoun.significance_text': 'The Nguoun represents a privileged moment of communion and reunion for the Bamoun people. It is an opportunity to renew community bonds, pass on ancestral knowledge to younger generations and celebrate Bamoun cultural identity in all its richness and diversity.',
    'nguoun.videos_title': 'Nguoun September 2024 Videos',

    // Galerie Page
    'galerie.badge': 'Photos & Media',
    'galerie.title': 'Our',
    'galerie.title_highlight': 'Gallery',
    'galerie.subtitle': 'Discover in images the highlights of our community and events.',

    // Partenaires Page
    'partenaires.badge': 'Our Partners',
    'partenaires.title': 'Our',
    'partenaires.title_highlight': 'Partners',
    'partenaires.subtitle': 'The organizations and institutions supporting our mission to preserve heritage.',
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('imh-language');
    return (saved === 'en' || saved === 'fr') ? saved : 'fr';
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('imh-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
